// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Binding.iOS.Views;
using SharedPcl.DataModels;
using UIKit;

namespace RealmMvxCollectionViewTestCase
{
	public partial class CollectionCell : MvxCollectionViewCell
	{
		private readonly MvxImageViewLoader _imageViewLoader;

		public CollectionCell(IntPtr handle) : base (handle)
		{
			_imageViewLoader = new MvxImageViewLoader(() => this.ImageViewCat);

			this.DelayBind(() =>
			{
				Debug.WriteLine("Bind");
				var set = this.CreateBindingSet<CollectionCell, Cat>();
				set.Bind(_imageViewLoader).For(x => x.ImageUrl).To(c => c.ImageUrl);
				set.Bind(LabelName).To(c => c.Name);
				set.Apply();
			});
		}
	}
}
